"""Add some columns for pre-fill on MatchForm

Revision ID: 147052e4bfe3
Revises: f6d7bd2fb445
Create Date: 2025-08-22 15:31:23.849339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147052e4bfe3'
down_revision = 'f6d7bd2fb445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_league', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('away_team_league', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('home_team_league_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('away_team_league_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('favorite_player_side', sa.Enum('home', 'away', name='favorite_side'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('favorite_player_side')
        batch_op.drop_column('away_team_league_id')
        batch_op.drop_column('home_team_league_id')
        batch_op.drop_column('away_team_league')
        batch_op.drop_column('home_team_league')

    # ### end Alembic commands ###
