"""Add team_id and team name fields to match

Revision ID: 1ef6e097b758
Revises: e860154663bd
Create Date: 2025-08-21 11:45:49.252118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef6e097b758'
down_revision = 'e860154663bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('away_team_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('away_team_id')
        batch_op.drop_column('home_team_id')

    # ### end Alembic commands ###
