"""Add team_logo table

Revision ID: 289e5606870e
Revises: 39983a759ff0
Create Date: 2025-08-28 15:16:51.582351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289e5606870e'
down_revision = '39983a759ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_logos',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_logos')
    # ### end Alembic commands ###
