"""add some relationships

Revision ID: 39983a759ff0
Revises: f417be3abc6a
Create Date: 2025-08-26 11:22:49.665476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39983a759ff0'
down_revision = 'f417be3abc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_favorite', ['user_id', 'trip_id'])

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_follow', ['follower_id', 'followed_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint('unique_follow', type_='unique')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('unique_favorite', type_='unique')

    # ### end Alembic commands ###
