"""fix league columns as nullable

Revision ID: 7c38b34277f6
Revises: e1aeff87ecb0
Create Date: 2025-08-22 15:41:28.913793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c38b34277f6'
down_revision = 'e1aeff87ecb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_league', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('away_team_league', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('home_team_league_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_team_league_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_side', sa.Enum('home', 'away', name='favorite_side'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('favorite_side')
        batch_op.drop_column('away_team_league_id')
        batch_op.drop_column('home_team_league_id')
        batch_op.drop_column('away_team_league')
        batch_op.drop_column('home_team_league')

    # ### end Alembic commands ###
