"""Add cascade delete to favorites.trip_id

Revision ID: 8d16c3777a98
Revises: 2b6337d2c2dd
Create Date: 2025-08-19 16:08:23.719471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d16c3777a98'
down_revision = '2b6337d2c2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('favorites_trip_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trip', ['trip_id'], ['trip_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('favorites_trip_id_fkey'), 'trip', ['trip_id'], ['trip_id'])

    # ### end Alembic commands ###
