"""fix league columns as nullable

Revision ID: e1aeff87ecb0
Revises: 147052e4bfe3
Create Date: 2025-08-22 15:40:14.732854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1aeff87ecb0'
down_revision = '147052e4bfe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_league', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('away_team_league', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('home_team_league_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_team_league_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_player_side', sa.Enum('home', 'away', name='favorite_side'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('favorite_player_side')
        batch_op.drop_column('away_team_league_id')
        batch_op.drop_column('home_team_league_id')
        batch_op.drop_column('away_team_league')
        batch_op.drop_column('home_team_league')

    # ### end Alembic commands ###
