"""fix league columns as nullable

Revision ID: f417be3abc6a
Revises: 49d190022144
Create Date: 2025-08-22 15:42:49.242265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f417be3abc6a'
down_revision = '49d190022144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_league', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('away_team_league', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('home_team_league_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_team_league_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_side', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('favorite_side')
        batch_op.drop_column('away_team_league_id')
        batch_op.drop_column('home_team_league_id')
        batch_op.drop_column('away_team_league')
        batch_op.drop_column('home_team_league')

    # ### end Alembic commands ###
