"""Add league and league_id to Us
er

Revision ID: f6d7bd2fb445
Revises: 1ef6e097b758
Create Date: 2025-08-22 10:25:14.178872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d7bd2fb445'
down_revision = '1ef6e097b758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('league_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('league_id')
        batch_op.drop_column('league')

    # ### end Alembic commands ###
