"""destroy and recreate tables for prediction

Revision ID: f6fbc061c146
Revises: 5406f8202022
Create Date: 2025-09-03 09:04:47.285402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6fbc061c146'
down_revision = '5406f8202022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('result_prediction', sa.String(), nullable=False),
    sa.Column('score_home_prediction', sa.Integer(), nullable=True),
    sa.Column('score_away_prediction', sa.Integer(), nullable=True),
    sa.Column('total_goals_prediction', sa.Integer(), nullable=True),
    sa.Column('red_card_prediction', sa.Boolean(), nullable=True),
    sa.Column('obtained_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.prediction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('match_one_away')
        batch_op.drop_column('match_two_away_id')
        batch_op.drop_column('match_three_home_id')
        batch_op.drop_column('match_one_home_id')
        batch_op.drop_column('match_three_home')
        batch_op.drop_column('match_one_id')
        batch_op.drop_column('match_three_away_id')
        batch_op.drop_column('match_one_prediction')
        batch_op.drop_column('match_two_home')
        batch_op.drop_column('match_two_id')
        batch_op.drop_column('match_three_prediction')
        batch_op.drop_column('match_one_point')
        batch_op.drop_column('match_three_point')
        batch_op.drop_column('match_three_away')
        batch_op.drop_column('match_one_home')
        batch_op.drop_column('match_one_away_id')
        batch_op.drop_column('match_two_away')
        batch_op.drop_column('bonus_awarded')
        batch_op.drop_column('match_two_home_id')
        batch_op.drop_column('match_two_point')
        batch_op.drop_column('match_two_prediction')
        batch_op.drop_column('match_three_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_three_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_two_prediction', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_two_point', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_two_home_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bonus_awarded', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_two_away', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_one_away_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_one_home', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_three_away', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_three_point', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_one_point', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_three_prediction', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_two_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_two_home', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_one_prediction', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_three_away_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_one_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_three_home', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_one_home_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_three_home_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_two_away_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_one_away', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('prediction_match')
    # ### end Alembic commands ###
